# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b6decb034a6770e0f5a4979e38eb53c5b3f1957a95c7672ce21cb2e6817a31030ae957994ff88e6df33ba1fbbb9ccb5e6dd25f8f61cda5b82eadd8b0ce39ee

test:
  secret_key_base: 3b79b4fcf638e42e45dde49728aa3adabb57239f290d76418fc5504a99a5d78bd397ce302c9a9d8c3a83e14a30ede0f6548ebb33b4f93b3c5e0ccc4dc872bf2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
